## NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

### Installation Instructions
It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:

**conda install numpy**

You can use this link to learn more about *Numpy*
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.html

### Using NumPy
Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

**arange**
:Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones

Generate arrays of zeros or ones

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((1,5)) 

array([[0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,3)) + np.ones((3,3))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [21]:
np.ones((2,2)) + np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [28]:
## It takes the first element, last element, and splits it into number of elements specified
np.linspace(0,10,3)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
a = np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
## You can also iterate through it using for loop
from math import sin
for i in a:
    print(sin(i))

0.0
0.8414709848078965
0.9092974268256817
0.1411200080598672
-0.7568024953079282
-0.9589242746631385
-0.27941549819892586
0.6569865987187891
0.9893582466233818
0.4121184852417566
-0.5440211108893698


In [41]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix[0][1]

2

In [42]:
for i in range(my_matrix.shape[0]):
    for j in range(my_matrix.shape[1]):
        print(my_matrix[i][j])
        
        
# i = 0, j = 0, 
# i = 0, j = 1,


# i = 1, j = 0, 
# i = 1, j = 1,


# i = 2, j = 0, 
# i = 2, j = 1


1
2
3
4
5
6
7
8
9


### Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [47]:
np.random.rand(2)

array([0.58959719, 0.80931527])

In [48]:
np.random.rand(5,5)

array([[0.24501366, 0.628692  , 0.41292645, 0.84910253, 0.06743643],
       [0.06178695, 0.63389671, 0.95844521, 0.23881264, 0.03512613],
       [0.15290139, 0.74474216, 0.09716683, 0.54387161, 0.68591081],
       [0.77629286, 0.64308329, 0.71123344, 0.94247078, 0.3375926 ],
       [0.18953168, 0.99335425, 0.94899648, 0.82711056, 0.91699526]])

In [55]:
## make sure that we get the same random numbers we ewant eevery time
np.random.seed(132131)
np.random.rand(2)

array([0.74016278, 0.71073306])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [58]:
#np.random.randint(start,end,how manynumbers you want)
np.random.randint(1,100,10)

array([89, 59, 15, 92, 98, 27, 87, 14, 78, 71])

In [61]:
arr = np.arange(10)
ranarr = np.random.randint(0,50,10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
ranarr

array([25, 30, 11, 15, 37,  5, 21, 26, 12, 41])

In [63]:
arr.shape

(10,)

In [67]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
arr.reshape(10,1).shape

(10, 1)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [71]:
ranarr

array([25, 30, 11, 15, 37,  5, 21, 26, 12, 41])

In [72]:
ranarr.max()

41

In [73]:
ranarr.min()

5

In [74]:
ranarr.argmax()

9

In [75]:
ranarr.argmin()

5

### dtype

You can also grab the data type of the object in the array:

In [78]:
arr = np.arange(10)
arr.dtype

dtype('int32')

In [79]:
a = np.array([1.0,2.0])

In [80]:
a.dtype

dtype('float64')

In [81]:
np.array([True,False]).dtype

dtype('bool')

In [82]:
z =  np.arange(0,11,2)
z


array([ 0,  2,  4,  6,  8, 10])

In [83]:
z.dtype

dtype('int32')

In [84]:
z.astype('float64')

array([ 0.,  2.,  4.,  6.,  8., 10.])

### NumPy Indexing and Selection

In [85]:
#Creating sample array
arr = np.arange(0,21,2)

In [86]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
#Get a value at an index
arr[8]

16

In [89]:
#Get values in a range
arr[1:5] # inclding 1 and excluding 5

array([2, 4, 6, 8])

### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [92]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [93]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [96]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [97]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [99]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

## to make a copy for list
ls = [1,2,3,4,5,6]
ls_copy = ls.copy()


[1, 2, 3, 4, 5, 6]

In [100]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [102]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [104]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [105]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [118]:
#Set up matrix
arr2d = np.zeros((10,10))

In [119]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
#Length of array
arr_length = arr2d.shape

In [111]:
type(arr_length)

tuple

In [112]:
arr_length = arr2d.shape[1] #stores the column of the matrix

In [121]:
#Set up array
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [122]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [123]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [127]:
bool_arr = arr>4

In [128]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [129]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [130]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [132]:
x = 4
arr[arr<x]

array([1, 2, 3])

## NumPy Operations

In [133]:
arr = np.arange(0,10)

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [136]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [137]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
# Warning on division by zero, but not an error!
# Just replaced with nan
x = arr/arr
x[0] = 0
x
### Python replaces the missing data with NAN

C:\Users\Divyanshu Singhal\Anconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [139]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array

In [146]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [147]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [148]:
np.max(arr) #same as arr.max()

9

In [149]:
arr.max()

9

In [150]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [151]:
from numpy import sin

In [152]:
sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [143]:
import math

In [ ]:
math.sin(arr)

In [145]:
math.sin(1)

0.8414709848078965

In [ ]:
math.sin(1)

In [ ]:
from math import pi

In [ ]:
pi

In [ ]:
math.sin(pi/2)